import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		//int T = Integer.parseInt(args[0]);
		//int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
       // Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		
		//*
		boolean girl, boy;
	int T = Integer.parseInt(args[0]);
	int seed = Integer.parseInt(args[1]);
	Random generator = new Random(seed);
	int count2C = 0;
	int count3C = 0;
	int count4C = 0;
	int sum = 0;
	double n = Double.parseDouble(args[0]);
	int max;
	double average;

	for (int i = 0; i < T; i++) {
		girl = false;
		boy = false;
		int count = 0;

		while ((!girl) || (!boy)) {
			//double random = Math.random();
			double random = generator.nextDouble();
			if (random >= 0.5) {
				girl = true;
			} else {
				boy = true;
			}
			count++;
		}

		sum += count;

		if (count >= 4) {
			count4C++;
		} else if (count == 3) {
			count3C++;
		} else if (count == 2) {
			count2C++;
		}
	}

	int tempmax = Math.max(count2C, count3C);
	max = Math.max(tempmax, count4C);
	average = sum / T;

	System.out.println("Average: " + average + " children to get at least one of each gender.");
	System.out.println("Number of families with 2 children: " + count2C);
	System.out.println("Number of families with 3 children: " + count3C);
	System.out.println("Number of families with 4 children: " + count4C);

	if (max == count4C) {
		System.out.println("The most common number of children is 4 or more.");
	} else if (max == count2C) {
		System.out.println("The most common number of children is 2.");
	} else {
		System.out.println("The most common number of children is 3.");
	} 
		*//
		        boolean girl, boy;
        int T = Integer.parseInt(args[0]);
        int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);
        int count2C = 0;
        int count3C = 0;
        int count4C = 0;
        int sum = 0;
        int max;
        double average;

        for (int i = 0; i < T; i++) {
            girl = false;
            boy = false;
            int count = 0;

            while ((!girl) || (!boy)) {
                double random = generator.nextDouble();
                if (random >= 0.5) {
                    girl = true;
                } else {
                    boy = true;
                }
                count++;
            }

            sum += count;

            if (count >= 4) {
                count4C++;
            } else if (count == 3) {
                count3C++;
            } else if (count == 2) {
                count2C++;
            }
        }

        int tempmax = Math.max(count2C, count3C);
        max = Math.max(tempmax, count4C);
        average = (double) sum / T;

        System.out.println("Average: " + average + " children to get at least one of each gender.");
        System.out.println("Number of families with 2 children: " + count2C);
        System.out.println("Number of families with 3 children: " + count3C);
        System.out.println("Number of families with 4 or more children: " + count4C);

        if (max == count4C) {
            System.out.println("The most common number of children is 4 or more.");
        } else if (max == count2C) {
            System.out.println("The most common number of children is 2.");
        } else {
            System.out.println("The most common number of children is 3.");
        }
	}
}
